### ISSUE TITLE
Cannot Install - nginx proxy_read_timeout wrong value

### ISSUE THREAD

**Issue by Krakinou** [YunoHost-Apps/filebrowser_ynh#13]
Hello
I cannot install filebrowser on my Yunohost
Here is the full log: https://paste.yunohost.org/raw/nutozewuha

I noticed this line that seems to be the issue: 
`2022-07-03 00:04:29,796: DEBUG - juil. 03 00:04:29 nginx[11120]: nginx: [emerg] "proxy_read_timeout" directive invalid value in /etc/nginx/conf.d/maindomain.tld.d/filebrowser.conf:21`

**Comment by ericgaspar** [comment]
#14 should fix the issue
