### ISSUE TITLE
Setting directory in file browser 

### ISSUE THREAD

**Issue by Chevrah** [YunoHost-Apps/filebrowser_ynh#26]
Can we change the directory to work for /home/yunohost.multimedia?

**Comment by ericgaspar** [comment]
Did you try? (cf. https://github.com/YunoHost-Apps/filebrowser_ynh/blob/master/doc/ADMIN.md)

**Comment by ericgaspar** [comment]
This is present on the main page of the ynh package description.

**Comment by mateMathieu** [comment]
Yes, thank for pointing it to me. I installed it some time ago and I didn't find it at that time. My bad.
