### ISSUE TITLE
Filebrowser upgrade from 2.28.0~ynh1 to 2.29.0~ynh1 removes database.db

### ISSUE THREAD

**Issue by MadMan247** [YunoHost-Apps/filebrowser_ynh#44]
Upon upgrading from 2.28.0 to 2.29.0, I was unable to log in to any of my previously setup accounts, including the admin account (I had changed the name AND password). I had thought that I was just mistyping the password over and over somehow, or fail2ban was keeping me from attempting, but ultimately when I restored 2.28.0~ynh1, I was immediately able to log in.

### Context

- Hardware: Raspberry Pi at home (4B 4GB)
- YunoHost version: 11.2.11.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 2.28.0\~ynh1 to 2.29.0\~ynh1

### Steps to reproduce

Update Filebrowser
Attempt to log in
be rejected

![image](https://github.com/YunoHost-Apps/filebrowser_ynh/assets/54383546/d4a14c9a-7339-4b2a-b5e9-9412b0015948)

admin admin is the default login again

### Expected behavior

My previous login attempts would have allowed me to log in to my previously set up accounts. I have upgraded again to the same result, so this was not a fluke.

### Logs

https://paste.yunohost.org/delevotaya
(log contains login attempts after updating)

all previous users nuked 
![image](https://github.com/YunoHost-Apps/filebrowser_ynh/assets/54383546/cee02485-2db4-4d61-8d2a-7b2818d80ff0)

**Comment by borisnoyet** [comment]
I encountered exactly the same issues here when upgrading from 2.28.0 to 2.30.0
Here is the log of the update : [https://paste.yunohost.org/raw/xopigoqaye](https://paste.yunohost.org/raw/xopigoqaye)

- Hardware: Mini PC x86-64 at home (16 GB)
- YunoHost version: 11.2.12 (stable)
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 2.28.0~ynh1 to 2.30.0~ynh1
